AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.workspace/**/*'
    - 'bundle/**/*'

# Lint
Lint/UselessMethodDefinition:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

# LStylent
Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Metrics
Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/MethodLength:
  Max: 60

Metrics/BlockLength:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'

# Naming
Naming/VariableNumber:
  EnforcedStyle: snake_case

# Bundler
Bundler/OrderedGems:
  Enabled: false